var srcIndex = JSON.parse('{\
"acpi":["",[],["fadt.rs","lib.rs","madt.rs"]],\
"anyhow":["",[],["backtrace.rs","chain.rs","context.rs","ensure.rs","error.rs","fmt.rs","kind.rs","lib.rs","macros.rs","ptr.rs","wrapper.rs"]],\
"bitflags":["",[],["external.rs","internal.rs","iter.rs","lib.rs","parser.rs","public.rs","traits.rs"]],\
"bytemuck":["",[],["anybitpattern.rs","checked.rs","contiguous.rs","internal.rs","lib.rs","no_uninit.rs","offset_of.rs","pod.rs","pod_in_option.rs","transparent.rs","zeroable.rs","zeroable_in_option.rs"]],\
"elf":["",[],["dynamic.rs","lib.rs","reloc.rs","section.rs","segment.rs","symbol.rs","types.rs"]],\
"fdt":["",[],["lib.rs","node.rs","parser.rs","prop.rs"]],\
"gimli":["",[["read",[],["addr.rs","aranges.rs","cfi.rs","endian_slice.rs","index.rs","lists.rs","loclists.rs","mod.rs","op.rs","reader.rs","rnglists.rs","str.rs","util.rs","value.rs"]]],["arch.rs","common.rs","constants.rs","endianity.rs","leb128.rs","lib.rs"]],\
"libsa":["",[],["endian.rs","lib.rs","volatile.rs"]],\
"limine":["",[],["lib.rs"]],\
"linkset":["",[],["entry.rs","lib.rs","linkset_of.rs"]],\
"lock_api":["",[],["lib.rs","mutex.rs","remutex.rs","rwlock.rs"]],\
"log":["",[],["__private_api.rs","lib.rs","macros.rs"]],\
"sbi":["",[],["base.rs","hart_state_management.rs","ipi.rs","legacy.rs","lib.rs","performance_monitoring_unit.rs","rfence.rs","system_reset.rs","timer.rs"]],\
"scopeguard":["",[],["lib.rs"]],\
"spark":["",[["console",[],["mod.rs","sbi.rs"]],["dev",[["block",[["nvme",[],["controller.rs","identify.rs","mod.rs","queue.rs"]]],["mod.rs"]],["uart",[],["mod.rs","ns16550.rs"]]],["acpi.rs","fw_cfg.rs","mod.rs","pcie.rs"]],["fs",[["fat",[],["bpb.rs","dir.rs","mod.rs"]]],["mod.rs"]],["mem",[["pmm",[],["freelist_allocator.rs","init_ranges.rs","mod.rs"]]],["mod.rs","vmm.rs"]],["proto",[],["limine.rs"]],["sys",[["sbi",[],["mod.rs","start.rs"]],["uefi",[],["mod.rs"]]],["fdt.rs","mod.rs"]],["util",[],["maybe_static_arc.rs","mod.rs"]]],["config.rs","io.rs","malloc.rs","panic.rs","proto.rs","raw_symbol_map.rs","rtld.rs","smp.rs","spark.rs","time.rs","trap.rs"]],\
"spin":["",[["mutex",[],["spin.rs"]]],["barrier.rs","lazy.rs","lib.rs","mutex.rs","once.rs","relax.rs","rwlock.rs"]],\
"unwinding":["",[["unwinder",[["arch",[],["mod.rs","riscv64.rs"]],["find_fde",[],["fixed.rs","mod.rs"]]],["frame.rs","mod.rs"]]],["abi.rs","arch.rs","lib.rs","panic.rs","panicking.rs","personality.rs","util.rs"]],\
"uuid":["",[],["builder.rs","error.rs","external.rs","fmt.rs","lib.rs","macros.rs","parser.rs","timestamp.rs"]]\
}');
createSrcSidebar();
